/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thommil_animalsgo_cv_OpenCVProcessor */

#ifndef _Included_com_thommil_animalsgo_cv_OpenCVProcessor
#define _Included_com_thommil_animalsgo_cv_OpenCVProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thommil_animalsgo_cv_OpenCVProcessor
 * Method:    validateCapture
 * Signature: (Lcom/thommil/animalsgo/capture/Capture;)V
 */
JNIEXPORT void JNICALL Java_com_thommil_animalsgo_cv_OpenCVProcessor_validateCapture
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
